name: 'Fetch and Report GitHub Data'
description: 'Fetches GitHub data and reports in the Actions summary'
inputs:
  org_name:
    description: 'GitHub organization name'
    required: true
  repo_name:
    description: 'GitHub repository name'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_ORG_NAME: ${{ inputs.org_name }}
    INPUT_REPO_NAME: ${{ inputs.repo_name }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
